// Barrel exports for hooks
export { useCategories, useCreateCategory, useDeleteCategory } from './use-categories'
export { useLoans, useCreateLoan, useUpdateLoanStatus, useReturnLoan } from './use-loans'
export { useLocations } from './use-locations'
export { useNotifications, useMarkAsRead, useMarkAllAsRead } from './use-notifications'
export { useProfiles, useUpdateProfileRole, useToggleProfileActive } from './use-profiles'
export { useAppSettings, useUpdateAppSettings } from './use-settings'
export { useEmailTemplates, useUpdateEmailTemplate } from './use-email-templates'
export { usePlanning } from './use-planning'
export { useFormFields, useActiveFormFields, useCreateFormField, useUpdateFormField, useDeleteFormField } from './use-form-fields'
export { useNotificationRecipients, useCreateNotificationRecipient, useUpdateNotificationRecipient, useDeleteNotificationRecipient } from './use-notification-recipients'
export { useExtensionRequests, usePendingExtensions, useExtensionsByRequest, useCreateExtension, useApproveExtension, useRejectExtension } from './use-extension-requests'
export { useLoanRequests, useMyLoanRequests, useLoanRequest, useLoanRequestItems, useCreateLoanRequest, useUpdateRequestStatus, useCancelRequest, useProcessReturn } from './use-loan-requests'
export { useProductOptions, useAllProductOptions, useCreateProductOption, useUpdateProductOption, useDeleteProductOption } from './use-product-options'
export { useSubscriptionPlans, useAllSubscriptionPlans, useCreateSubscriptionPlan, useUpdateSubscriptionPlan, useDeleteSubscriptionPlan } from './use-subscription-plans'
export { useProducts, useProduct, useCreateProduct, useUpdateProduct, useDeleteProduct, useProductReservations, useReservationsInRange } from './use-products'
export { useThemeMode, useToggleTheme, useClearThemeOverride, useTheme } from './use-theme'
