-- =============================================================
-- Migration 128 — Complete the people directory from Azure AD.
--
-- The curated People list didn't cover every real user (nsaadi, vlorent…).
-- Add internal VO staff from the Azure AD export (person-like display names
-- on VO domains, no guests / shared mailboxes). People rows win on conflict.
-- Then re-run the profile backfill so these names land immediately.
-- =============================================================

BEGIN;

INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$adm-nexis@vogroupbxl.onmicrosoft.com$q$, $q$Adm Nexis$q$, $q$Adm$q$, $q$Nexis$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ababa@vo-europe.eu$q$, $q$Aki Baba$q$, $q$Aki$q$, $q$Baba$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$alice.segers@vo-event.be$q$, $q$Alice Segers$q$, $q$Alice$q$, $q$Segers$q$, $q$Senior Project Manager$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$aing@vo-europe.eu$q$, $q$Andrew Ing$q$, $q$Andrew$q$, $q$Ing$q$, $q$Senior Project Manager - (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$aabaci@vo-europe.eu$q$, $q$Anette Abaci$q$, $q$Anette$q$, $q$Abaci$q$, $q$Junior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$abculot@vo-group.be$q$, $q$Anne-Bénédicte Culot$q$, $q$Anne-Bénédicte$q$, $q$Culot$q$, $q$Business Development Manager$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$asarkisian@vo-europe.eu$q$, $q$Anush Sarkisian$q$, $q$Anush$q$, $q$Sarkisian$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$adebisschop@vo-group.be$q$, $q$Arnaud Debisschop$q$, $q$Arnaud$q$, $q$Debisschop$q$, $q$Sports Business Development Consultant$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$adayde@vo-europe.eu$q$, $q$Aurélien Daydé$q$, $q$Aurélien$q$, $q$Daydé$q$, $q$Project Manager (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$awards@vogroupbxl.onmicrosoft.com$q$, $q$Awards Eusew$q$, $q$Awards$q$, $q$Eusew$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$bcoenen@vo-group.be$q$, $q$Barbara Coenen$q$, $q$Barbara$q$, $q$Coenen$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$bschram@vo-event.be$q$, $q$Benoit Schram$q$, $q$Benoit$q$, $q$Schram$q$, $q$Senior Project Manager$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$cleanfestival@vo-event.be$q$, $q$Brussels Clean Festival$q$, $q$Brussels$q$, $q$Clean Festival$q$, $q$The organisation team$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$cdemeeus@vo-group.be$q$, $q$Camille De Meeûs$q$, $q$Camille$q$, $q$De Meeûs$q$, $q$Business Developer$q$, $q$TLV$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$cdelander@vo-europe.eu$q$, $q$Céline Delander$q$, $q$Céline$q$, $q$Delander$q$, $q$Resources & Finance Coordinator$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$cdion@vo-group.be$q$, $q$Céline Dion$q$, $q$Céline$q$, $q$Dion$q$, $q$Diva$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ckanama@vo-europe.eu$q$, $q$Clarisse Kanama$q$, $q$Clarisse$q$, $q$Kanama$q$, $q$Junior Project Manager$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$claude-ai@vo-group.be$q$, $q$Claude AI VOEUR$q$, $q$Claude$q$, $q$AI VOEUR$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$dbovee@vo-europe.eu$q$, $q$Daan Bovée$q$, $q$Daan$q$, $q$Bovée$q$, $q$Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$dining-room@vo-group.be$q$, $q$Dining Room$q$, $q$Dining$q$, $q$Room$q$, NULL, $q$VO GROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$dnsalambimundele@vo-group.be$q$, $q$Divine Nsalambi Mundele$q$, $q$Divine$q$, $q$Nsalambi Mundele$q$, $q$Cocreation & CSR communication officer$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$efrancois@vo-europe.eu$q$, $q$Elise François$q$, $q$Elise$q$, $q$François$q$, $q$Senior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$elitsa-ec-teams@vo-europe.eu$q$, $q$Elitsa EC-Teams$q$, $q$Elitsa$q$, $q$EC-Teams$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$energydays@vogroupbxl.onmicrosoft.com$q$, $q$Energy Days$q$, $q$Energy$q$, $q$Days$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ehereman@vo-group.be$q$, $q$Eric Hereman$q$, $q$Eric$q$, $q$Hereman$q$, $q$Consultant externe$q$, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$eubeelovers@vo-group.be$q$, $q$EU Beelovers$q$, $q$EU$q$, $q$Beelovers$q$, $q$Become a Beelover$q$, $q$BEELOVER$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$eu-roma-platform@vo-europe.eu$q$, $q$EU Roma Platform$q$, $q$EU$q$, $q$Roma Platform$q$, $q$Secretariat Team$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$euvsdisinfo_design@vo-europe.eu$q$, $q$EUvsDisinfo Design$q$, $q$EUvsDisinfo$q$, $q$Design$q$, $q$EUvsDisinfo Design$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$fbowen@vo-europe.eu$q$, $q$Federico Bowen$q$, $q$Federico$q$, $q$Bowen$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$feedbackcadre@vo-group.be$q$, $q$Feedback Cadre$q$, $q$Feedback$q$, $q$Cadre$q$, NULL, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$fbuttiens@vo-group.be$q$, $q$François Buttiens$q$, $q$François$q$, $q$Buttiens$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ftoper@vo-europe.eu$q$, $q$Fulya Toper$q$, $q$Fulya$q$, $q$Toper$q$, $q$NATO Edge 26 Local Operations Supervisor$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$gcapasso@vo-europe.eu$q$, $q$Giorgia Capasso$q$, $q$Giorgia$q$, $q$Capasso$q$, $q$Senior Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$glombi@vo-event.be$q$, $q$Grace Lombi$q$, $q$Grace$q$, $q$Lombi$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$hsleuwaegen@vo-event.be$q$, $q$Heidi Sleuwaegen$q$, $q$Heidi$q$, $q$Sleuwaegen$q$, NULL, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$hvaldesparra@vo-europe.eu$q$, $q$Helena Valdes Parra$q$, $q$Helena$q$, $q$Valdes Parra$q$, $q$EUSEW Secretariat Coordinator$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$hello@vo-group.be$q$, $q$Hello Voice$q$, $q$Hello$q$, $q$Voice$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$hnolet@vo-group.be$q$, $q$Héloîse Nolet$q$, $q$Héloîse$q$, $q$Nolet$q$, $q$Sustainability change maker$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$hbattistel@vo-europe.eu$q$, $q$Hugo Battistel$q$, $q$Hugo$q$, $q$Battistel$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$invoice@vo-group.be$q$, $q$Invoice VOG$q$, $q$Invoice$q$, $q$VOG$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$jdoe@vo-group.be$q$, $q$John Doe$q$, $q$John$q$, $q$Doe$q$, $q$Staging$q$, $q$VOE2025$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$jdenis@vo-event.be$q$, $q$Jordy Denis$q$, $q$Jordy$q$, $q$Denis$q$, $q$Project Executive$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$jroumeliotis@vo-europe.eu$q$, $q$Julie Roumeliotis$q$, $q$Julie$q$, $q$Roumeliotis$q$, $q$YCAP Support Team (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$jhuberlant@vo-event.be$q$, $q$Juliette Huberlant$q$, $q$Juliette$q$, $q$Huberlant$q$, $q$Project Developer$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$jthamm@vo-europe.eu$q$, $q$Juliette Thamm$q$, $q$Juliette$q$, $q$Thamm$q$, $q$Junior Project Manager (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$kzeroual@vo-europe.eu$q$, $q$Karim Zeroual$q$, $q$Karim$q$, $q$Zeroual$q$, $q$Junior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$kpasierbiewicz@vo-europe.eu$q$, $q$Kasia Pasierbiewicz$q$, $q$Kasia$q$, $q$Pasierbiewicz$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$knuyts@vo-event.be$q$, $q$Katrien Nuyts$q$, $q$Katrien$q$, $q$Nuyts$q$, NULL, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$kweyers@vo-event.be$q$, $q$Kevin Weyers$q$, $q$Kevin$q$, $q$Weyers$q$, $q$Project Manager$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$lfoulon@vo-group.be$q$, $q$Léa Foulon$q$, $q$Léa$q$, $q$Foulon$q$, $q$ESG & Sustainability team$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$lprovendier@vo-europe.eu$q$, $q$Léa Provendier$q$, $q$Léa$q$, $q$Provendier$q$, $q$Project Coordinator (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$laichele@vo-europe.eu$q$, $q$Léonore Aichele$q$, $q$Léonore$q$, $q$Aichele$q$, $q$Project Manager / Showcaller$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$lmedina@vo-europe.eu$q$, $q$Lia Medina$q$, $q$Lia$q$, $q$Medina$q$, $q$Project Manager (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$l.poznanski@vo-europe.eu$q$, $q$Lindsay Poznanski$q$, $q$Lindsay$q$, $q$Poznanski$q$, $q$Project Leader$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$lcallebaut@vo-event.be$q$, $q$Line Callebaut$q$, $q$Line$q$, $q$Callebaut$q$, NULL, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$llefevre@vo-event.be$q$, $q$Louise Lefevre$q$, $q$Louise$q$, $q$Lefevre$q$, $q$Project executive$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ltytgat@vo-event.be$q$, $q$Louise Tytgat$q$, $q$Louise$q$, $q$Tytgat$q$, NULL, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$lmazzanti@vo-europe.eu$q$, $q$Luca Mazzanti$q$, $q$Luca$q$, $q$Mazzanti$q$, $q$Project Coordinator - (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mmichelberger@vo-europe.eu$q$, $q$Maike Michelberger$q$, $q$Maike$q$, $q$Michelberger$q$, $q$Junior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mconstantinescu@vo-europe.eu$q$, $q$Maria Constantinescu$q$, $q$Maria$q$, $q$Constantinescu$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mmuller@vo-event.be$q$, $q$Marie Muller$q$, $q$Marie$q$, $q$Muller$q$, $q$Freelance Senior Project Manager$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$media@vogroupbxl.onmicrosoft.com$q$, $q$Media Eusew$q$, $q$Media$q$, $q$Eusew$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mculot@vo-group.be$q$, $q$Michel Culot$q$, $q$Michel$q$, $q$Culot$q$, $q$Board Member NouVO$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$m.estebanez@vo-europe.eu$q$, $q$Monica Estebanez$q$, $q$Monica$q$, $q$Estebanez$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mtakieddine@vo-event.be$q$, $q$Mouna Takieddine$q$, $q$Mouna$q$, $q$Takieddine$q$, $q$Project Developer$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$mkoraichi@vo-group.be$q$, $q$Moussa Koraichi$q$, $q$Moussa$q$, $q$Koraichi$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$nsaadi@vo-group.be$q$, $q$Nadir Saâdi$q$, $q$Nadir$q$, $q$Saâdi$q$, $q$IT Support - Intern$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ncpdays26@vo-europe.eu$q$, $q$NCP Training Days$q$, $q$NCP$q$, $q$Training Days$q$, $q$NCP 2026 secretariat$q$, $q$LIFE22 NETWORKING MEETING$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$networking@vogroupbxl.onmicrosoft.com$q$, $q$Networking Eusew$q$, $q$Networking$q$, $q$Eusew$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$nandrianjatovo@vo-event.be$q$, $q$Nikitah Andrianjatovo$q$, $q$Nikitah$q$, $q$Andrianjatovo$q$, $q$Assistante de production$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$nteso@vo-event.be$q$, $q$Nina Teso$q$, $q$Nina$q$, $q$Teso$q$, $q$Project Developer$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$fcmo-scic@vo-europe.eu$q$, $q$OLD FCMO SCIC$q$, $q$OLD$q$, $q$FCMO SCIC$q$, NULL, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$onlinepayment@vo-europe.eu$q$, $q$Online Payment$q$, $q$Online$q$, $q$Payment$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$olaouti@vo-group.be$q$, $q$Oussama Laouti$q$, $q$Oussama$q$, $q$Laouti$q$, $q$AI Advisor$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ptelek@vo-europe.eu$q$, $q$Patricia Telek$q$, $q$Patricia$q$, $q$Telek$q$, $q$Junior Project Manager$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$pparmentier@vo-group.be$q$, $q$Patrick Parmentier$q$, $q$Patrick$q$, $q$Parmentier$q$, $q$Board Member NouVO$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$pmaestre@vo-europe.eu$q$, $q$Pelayo Maestre$q$, $q$Pelayo$q$, $q$Maestre$q$, $q$Senior Project Manager$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$pmcevoy@vo-europe.eu$q$, $q$Philip McEvoy$q$, $q$Philip$q$, $q$McEvoy$q$, $q$Senior Copywriter (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$pthito@vo-europe.eu$q$, $q$Philippe Thito$q$, $q$Philippe$q$, $q$Thito$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$powerbi@vo-europe.eu$q$, $q$Power BI$q$, $q$Power$q$, $q$BI$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$registration@vogroupbxl.onmicrosoft.com$q$, $q$Registration Eusew$q$, $q$Registration$q$, $q$Eusew$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$rotsuka@vo-europe.eu$q$, $q$Reiko Otsuka$q$, $q$Reiko$q$, $q$Otsuka$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$rescue-it@vo-group.be$q$, $q$Rescue IT$q$, $q$Rescue$q$, $q$IT$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$samor@vo-event.be$q$, $q$Samira Amor$q$, $q$Samira$q$, $q$Amor$q$, $q$Project Leader$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$sginiatullina@vo-europe.eu$q$, $q$Saniya Giniatullina$q$, $q$Saniya$q$, $q$Giniatullina$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$snishida@vo-europe.eu$q$, $q$Saori Nishida$q$, $q$Saori$q$, $q$Nishida$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$seso@vo-europe.eu$q$, $q$Serge Somerling$q$, $q$Serge$q$, $q$Somerling$q$, $q$Project Manager (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ssomerling@vo-event.be$q$, $q$Serge Somerling$q$, $q$Serge$q$, $q$Somerling$q$, $q$Sr. Project Manager$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$g3906edb708d14138bef07d947886a8d8@vo-group.be$q$, $q$SIGN Brussels$q$, $q$SIGN$q$, $q$Brussels$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$info-sm30@vo-europe.eu$q$, $q$Single Market Tour$q$, $q$Single$q$, $q$Market Tour$q$, $q$Organising team$q$, $q$INFO SM30 TOUR$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$some@vo-group.be$q$, $q$SoMe TLV$q$, $q$SoMe$q$, $q$TLV$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$sdive@vo-group.be$q$, $q$Sophie Dive$q$, $q$Sophie$q$, $q$Dive$q$, $q$Business Developer$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$smccoy@vo-group.be$q$, $q$Sophie McCoy$q$, $q$Sophie$q$, $q$McCoy$q$, $q$Business Developer$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$swalckiers@vo-europe.eu$q$, $q$Stephen Walckiers$q$, $q$Stephen$q$, $q$Walckiers$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$srouyre@vo-europe.eu$q$, $q$Steve Rouyre$q$, $q$Steve$q$, $q$Rouyre$q$, $q$Project Manager Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$sumup@vo-europe.eu$q$, $q$SumUp VOEUR$q$, $q$SumUp$q$, $q$VOEUR$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$sgoncalves@vo-europe.eu$q$, $q$Susana Gonçalves Fernandes$q$, $q$Susana$q$, $q$Gonçalves Fernandes$q$, $q$Junior Project Manager - (consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$sluyckx@vo-event.be$q$, $q$Sylvie Luyckx$q$, $q$Sylvie$q$, $q$Luyckx$q$, $q$Project Developer$q$, $q$VOEVENT$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$tverrept@vo-group.be$q$, $q$Tom Verrept$q$, $q$Tom$q$, $q$Verrept$q$, $q$VENTURE BUILDER$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$vseaman@vo-europe.eu$q$, $q$Veera Seaman$q$, $q$Veera$q$, $q$Seaman$q$, $q$Junior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$vdobrev@vo-europe.eu$q$, $q$Venelin Dobrev$q$, $q$Venelin$q$, $q$Dobrev$q$, $q$Social Media Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$vlorent@vo-europe.eu$q$, $q$Vladimir Lorent$q$, $q$Vladimir$q$, $q$Lorent$q$, $q$Junior Project Management intern$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$webinar@vogroupbxl.onmicrosoft.com$q$, $q$Webinar Euseuw$q$, $q$Webinar$q$, $q$Euseuw$q$, NULL, NULL, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$wnicolai@vo-group.be$q$, $q$Wim Nicolaï$q$, $q$Wim$q$, $q$Nicolaï$q$, $q$Business Growth & Tender Manager$q$, $q$VOGROUP$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$wini@vo-europe.eu$q$, $q$Wim Nicolaï$q$, $q$Wim$q$, $q$Nicolaï$q$, $q$NATO Edge 26 Project Director$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$ymotobe@vo-europe.eu$q$, $q$Yuka Motobe$q$, $q$Yuka$q$, $q$Motobe$q$, $q$Consultant$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO public.people_directory (email, full_name, first_name, last_name, job_title, business_unit, person_type, is_active) VALUES ($q$zbochinska@vo-europe.eu$q$, $q$Zofia Bochinska$q$, $q$Zofia$q$, $q$Bochinska$q$, $q$Junior Project Manager (Consultant)$q$, $q$VO EUROPE$q$, $q$employee$q$, TRUE) ON CONFLICT (email) DO NOTHING;

-- Backfill existing profiles again (only empty fields), now enriched.
UPDATE public.profiles p SET
  first_name    = COALESCE(NULLIF(p.first_name, ''), d.first_name),
  last_name     = COALESCE(NULLIF(p.last_name, ''),  d.last_name),
  phone         = COALESCE(NULLIF(p.phone, ''),         d.phone),
  job_title     = COALESCE(NULLIF(p.job_title, ''),     d.job_title),
  business_unit = COALESCE(NULLIF(p.business_unit, ''), d.business_unit),
  language      = COALESCE(NULLIF(p.language, ''),      d.language),
  department    = COALESCE(NULLIF(p.department, ''),    d.department)
FROM public.people_directory d
WHERE lower(p.email) = lower(d.email);

COMMIT;
